"use strict";
function getRandomQuote(ownedRoom) {
    if (Game.shard.name === "shard0") {
        return "The END is coming. Join the Church of the END";
    }
    if (ownedRoom) {
        return quote;
    }
    return quotes[Math.floor(Math.random() * quotes.length)];
}
exports.getRandomQuote = getRandomQuote;
;
const quote = "Operated by KasamiBot - https://kasami.github.io/kasamibot/";
const quotes = [
    "Life is about increasing GCL, not mining minerals. -Kevin Kruse",
    "Whatever the mind of creeps can conceive and believe, it can be programmed to. –Napoleon Hill",
    "Strive not to be a success, but rather to get to the next GCL. –Albert Einscreep",
    "I attribute my GCL to this: I never gave or took any excuse. –Florence Nightingale",
    "You miss 100% of the shots you don’t take. –Source Keeper Guard",
    "The most difficult thing is the decision to expand, the rest is merely tenacity. –Amelia Earhart",
    "Every upgrade brings me closer to the next GCL level. –Babe Ruth",
    "Definiteness of purpose is the starting point of all GCL. –W. Clement Stone",
    "Life isn't about getting and having, it's about increasing GCL. –Kevin Kruse",
    "Screeps code is what happens to you while you’re busy making other plans. –John Lennon",
    "We become what we program. –Earl Nightingale",
    "Life is 10% what happens to me and 90% of how I was programmed. –Charles Swindoll",
    "The code is everything. What you write you become. –Buddha",
    "An unexamined room is not worth scouting. –Socrates",
    "Eighty percent of success is upgrading. –Woody Allen",
    "Your time is limited to 1500 ticks, so don’t waste it living someone else’s life. –Steve Jobs",
    "Winning isn’t everything, but wanting to win is, and programming. –Vince Lombardi",
    "I am not a product of my circumstances. I am a product of my implementation. –Stephen Covey",
    "Either you run the code, or the code runs you. –Jim Rohn",
    "Whether you think you can or you think you can’t program screeps, you’re right. –Henry Ford",
    "The best revenge is massive GCL. –Frank Sinatra",
    "Life shrinks or expands in proportion to one's code. –Anais Nin",
    "There is only one way to avoid criticism: do nothing, say nothing, and code nothing. –Aristotle",
    "The only creep you are destined to become is the creep you where programmed to be. –Ralph Waldo Emerson",
    "Confidently expanding in direction of your dreams. Live the 1500 ticks you have imagined. –Henry David Thoreau",
    "Believe you can code and you’re halfway there. –Theodore Roosevelt",
    "Everything you’ve ever wanted is on the other side of the map. –George Addair",
    "Start where you are. Use what you have. Upgrade what you can. –Arthur Ashe",
    "When I let go of what I am, I become what I might be coded to be. –Lao Tzu",
    "Happiness is not something readymade. It comes from GCL. –Dalai Lama",
    "Too many of us are not coding our dreams because we are coding our fears. –Les Brown",
    "I didn’t fail at programming. I just found 100 ways to program it wrong. –Benjamin Franklin",
    "There are no traffic jams along the sector highways. –Roger Staubach",
    "It is never too late to program what you might have been. –George Eliot",
    "I would rather die of programming than of boredom. –Vincent van Gogh",
    "Build your own rooms, or someone else will hire you to build theirs. –Farrah Gray",
    "Power proccessing costs energy. But then so does ignorance. –Sir Claus Moser",
    "It does not matter how slowly you upgrade as long as you do not stop. –Confucius",
    "Expand quickly and dare to fail. –Norman Vaughan",
    "Do what you can, in your rooms, with what you have. –Teddy Roosevelt",
    "Dreaming, after all, is a form of programming. –Gloria Steinem",
    "The code is what we make it, always has been, always will be. –Grandma Moses",
    "It’s not the GCL in your life that count. It’s the life in your GCL. –Abraham Lincoln",
    "Change your code and you change your world. –Norman Vincent Peale",
    "The only way to write a great AI is to love what you do. –Steve Jobs",
    "If you can code it, you can achieve it. –Zig Ziglar",
    "You can code anything, but not everything. -David Allen",
    "CPU perfection is achieved, not when there is no more to add, but when there is no left to take away. -Antoine de Saint-Exupéry",
    "You must be the change you wish to see in the sector. -Gandhi",
    "To the man who only has a CLAIM, everything he encounters begins to look like a controller. -Abraham Maslow",
    "The real voyage of discovery consists not in seeking new features but using new code. -Marcel Proust",
    "Even if you’re on the right track, you’ll get run over if you just sit there without ramparts. - Will Rogers",
    "I’d rather live with a good spagetti code than a bad operating system. -Aryeh Frimer",
    "The cure for boredom is new features. There is no cure for featurehunger. -Ellen Parr",
    "The trouble with the creep race is that even if you win, you’re still a creep. -Lily Tomlin",
    "Only I can change my code. No one can do it for me. -Carol Burnett",
    "Optimism is the faith that leads to GCL. Nothing can be done without hope and confidence. -Helen Keller",
    "Our greatest weakness lies in giving up. The way to succeed is always to try more refactoring. -Thomas A. Edison",
    "The pathfinding algorithm always seems impossible until it's done. -Nelson Mandela",
    "Always do your best. What you reserve now, you will harvest later. -Og Mandino",
    "With the new day comes new code and new refactoring. -Eleanor Roosevelt",
    "The past code revisions cannot be changed. The future code is yet in your power. -Unknown",
    "Boosted attackers will never overtake me if my determination to succeed is strong enough. -Og Mandino",
    "Setting goals is the first step in turning the ideas into code. -Tony Robbins",
    "You can't cross the highways merely by standing and staring at the portal room. -Rabindranath Tagore",
    "Code quality is not an act, it is a habit. -Aristotle",
    "If you can dream it, you can code it. -Disney",
    "Accept the code challenges so that you can fell the exhilaration of victory. -George S. Patton",
    "The secret of getting ahead is getting started with coding. -Mark Twain",
    "Keep your eyes on the stars, your feet on the ground, and fingers on the keyboard. -Theodore Roosevelt",
    "If you got wiped out yesterday, respawn today. -H. G. Wells",
    "Either remove or be removed. -Ezra Pound",
    "You are never too old to resettle or code another architecture. -Les Brown",
    "Don't watch the creeps; do what they do. Keep upgrading. -Sam Levenson",
    "When a room is important enough, you attack it even if the odds are not in your favor. -Elon Musk",
    "Your GCL is Screeps's gift to you. What you do with it is your gift back to Screeps. -Leo Buscaglia",
    "A creative man is motivated by the desire to code, and by the desire to beat others. -Ayn Rand",
    "Upgrade the controller whenever possible. It is always possible. -Dalai Lama",
    "Set your goals high, and don't stop coding till you get there. -Bo Jackson",
    "If you want to conquer fear, don't sit home and think about it. Grab a bear and start coding. -Dale Carnegie",
    "Well coded is better than well pseudocoded. -Benjamin Franklin",
    "There is only one part of screeps you can be certain of improving, and that's your own code. -Aldous Huxley",
    "Aim for the Source Keeper. If you miss, you may hit the portal. -W. Clement Stone",
    "Screeps is the art of getting creeps to do what you want them to do because they want to do it. -Dwight D. Eisenhower",
    "I'd rather attempt to write code great and fail than to copy code and succeed. -Robert H. Schuller",
    "Things do not happend. Things are coded to happen. -John F. Kennedy",
    "By failing to prepare for attacks, you are preparing to fail. -Benjamin Franklin",
    "Do you want to know who you are? Don't ask. Code. The code will delineate and define you. -Thomas Jefferson",
    "I am not afraid... I was coded to do this. -Joan of Arc",
    "Good code violently executed now is better than perfect code executed next week. -George S. Patton",
    "What you code today can improve all your tomorrows. -Ralph Marston",
    "Code something wonderful, people may imitate it. -Albert Schweitzer",
    "Opportunity does not knock, it presents itself when you invade the sector. -Kyle Chandler",
    "The most effective way to code it, is to code it. -Amelia Earhart",
    "If you don't like how things are, refactor. You're not an OCS-member. -Jim Rohn",
    "The will to succeed is important, but what's more important is to upgrade. -Bobby Knight",
    "The ultimate aim of the ego is not to read code, but to write code. -Muhammad Iqbal",
    "There's a way to code it better - find it. -Thomas A. Edison",
    "You just can't beat the person who never stops respawning. -Babe Ruth",
    "Code as if what you do makes a difference. It does. -William James",
    "Code your AI with your whole heart, and you will succeed - there's so little competition. -Elbert Hubbart",
    "Go for it now. The sector is promised to no one. -Wayne Dyer",
    "Change your code today. Don't gamble on the future, act now, without delay. -Simone de Beauvoir",
    "It's always too early to quit upgrading. -Norman Vincent Peale",
    "You can't build a reputation on what you are going to code. -Henry Ford",
    "Small code snippets implemented are better than great features planned. -Peter Marshall",
    "There is nothing deep down inside us except what we have coded ourselves. -Rickard Rorty",
    "When one must code in the console, one can. -Charlotte Whitton",
    "Get action. Seize the moment. Creeps was never intended to become a container. -Theodore Roosevelt",
    "Begin to code now what you will be hereafter. -William James",
    "Success in the only motivational factor that a screeps player with character needs. -Woody Hayes",
    "There is progress whether ye are going forward or backward. The thing is to upgrade. -Edgar Cayce",
    "I code, therefore I am. -Simone Weil"
];
